kind: pipeline
type: docker
name: default

common: &build
  image: python:3.8
  commands:
    - pwd
    - ls -a
    - pipenv install --system
    - python src/main.py

steps:
- name: greeting
  <<: *build
  when:
    events:
      - pull_requests

- name: merge
  <<: *build
  commands:
    - pipenv install --system
    - python main2.py
  when:
    branch:
      - master