kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: python:3.7
  commands:
    - pwd
    - ls -a
    - pip install pipenv
    - pipenv install --system
    - python src/main.py
  when:
    branch:
      exclude:
        - master
    events:
      - pull_request

- name: merge
  image: python:3.7
  commands:
    - pip install pipenv
    - pipenv install --system
    - python main2.py
  when:
    branch:
      - master
    events:
      push
