kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/myreviewdog:latest
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    # REVIEWDOG_GITHUB_API_TOKEN:
    #   from_secret: reviewdog
  commands:
    - . /src/token2env.sh
    - echo $REVIEWDOG_GITHUB_API_TOKEN
    - reviewdog -conf=./.reviewdog.yml -reporter=github-pr-review

  when:
    event:
      - pull_request
