kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    DOCKER_API_VERSION: 1.39
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  commands:
    - echo $PATH
    - which rp_reviewdog
    - rp_reviewdog src
  when:
    event:
      - pull_request
