kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    # REVIEWDOG_GITHUB_API_TOKEN:
    #   from_secret: reviewdog
  commands:
    - ls -l /
    - . /report.sh

  when:
    event:
      - pull_request
