kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    DOCKER_API_VERSION: 1.39
    PRIVATE_KEY:
      from_secret: private_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  commands:
    # - rp_reviewdog ./src/
    - python /src/rp_reviewdog.py --dir=./src
    # - python /src/module/gettoken.py
    # - export REVIEWDOG_GITHUB_API_TOKEN=$(cat /src/token.conf)
    # - flake8 ./src/ | reviewdog -reporter=github-pr-review -f=pep8 -diff="git diff master"
    # - python src/pygithub_playground/hello.py
    # - echo $PATH
    # - sh test.sh
    # - which pr_comment
    # - ls -l /src
    # - rp_reviewdog src/
    # - pr_comment content
    # - rp_pytest src/
  when:
    event:
      - pull_request
