kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  commands:
    - ls -l /
    - echo $GIT_REVISION
    # - echo $DRONE_REPO_OWNER
    # - echo $DRONE_REPO_NAME
    # - echo $DRONE_PULL_REQUEST
    # curl テスト用
    - . /drone/src/test.sh
  when:
    event:
      - pull_request
