kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  image: myreviewdog
  environment:
    REVIEWDOG_GITHUB_API_TOKEN:
      from_secret: reviewdog
  commands:
    - pipenv install --dev --system
    - pip freeze
    - ./bin/reviewdog -conf=./.reviewdog.yml -reporter=github-pr-review
  when:
    event:
      - pull_request

- name: merge
  image: python:3.7
  commands:
    - pip install pipenv
    - pipenv install --system
    - python main2.py
  when:
    branch:
      - master
    event:
      - push
