kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  commands:
    - ls -l /
    # curl テスト用
    - python /src/get_token.py
    - export REVIEWDOG_GITHUB_API_TOKEN=`cat /src/token.conf`
    - echo $REVIEWDOG_GITHUB_API_TOKEN
    - curl -X POST \
           -H "Authorization: token ${REVIEWDOG_GITHUB_API_TOKEN}" \
           -d "{\"body\": \"hello world\"}" \
           https://github.com/Yashikab/drone_yml_practice/pull/15
  when:
    event:
      - pull_request
