kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  image: yashikab/myreviewdog:latest
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    # REVIEWDOG_GITHUB_API_TOKEN:
    #   from_secret: reviewdog
  commands:
    - pipenv install --dev --system
    - pip freeze
    - python src/get_token.py
    - ls -a
    - token_content=`cat token.conf`
    - export REVIEWDOG_GITHUB_API_TOKEN=$token_content
    - echo $REVIEWDOG_GITHUB_API_TOKEN
    - which reviewdog
    - echo $PATH
    - reviewdog -conf=./.reviewdog.yml -reporter=github-pr-review
    - rm token.conf
  when:
    event:
      - pull_request

# - name: gettoken
#   image: python:3.7
#   environment:
#     PRIVATE_KEY:
#       from_secret: github_pri_key
#     APP_ID:
#       from_secret: app_id
#     INSTALLATION_ID:
#       from_secret: installation_id
#   commands:
#     - pip install pipenv
#     - pipenv install --system
#     - python src/get_token.py
#   when:
#     branch:
#       exclude:
#         - master
#     event:
#       - push
# - name: merge
#   image: python:3.7
#   commands:
#     - pip install pipenv
#     - pipenv install --system
#     - python main2.py
#   when:
#     branch:
#       - master
#     event:
#       - push
