kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: python:3.7
  commands:
    - echo "install reviewdog"
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
    - pip install pipenv
    - pipenv install --system
    - python src/main.py
  when:
    event:
      - pull_request

- name: merge
  image: python:3.7
  commands:
    - pip install pipenv
    - pipenv install --system
    - python main2.py
  when:
    branch:
      - master
    event:
      - push
