kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: python:3.7
  environment:
    REVIEWDOG_GITHUB_API_TOKEN:
      from_secret: reviewdog
  commands:
    - echo "install reviewdog"
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
    - pip install pipenv
    - pipenv install --system
    - echo $REVIEWDOG_GITHUB_API_TOKEN
    - ls -a
    - pycodestyle ./src/ | ./bin/reviewdog -reporter=github-pr-review
  when:
    event:
      - pull_request

- name: merge
  image: python:3.7
  commands:
    - pip install pipenv
    - pipenv install --system
    - python main2.py
  when:
    branch:
      - master
    event:
      - push
