kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  commands:
    - ls -l /
    - . /report.sh ./src
    - echo $REVIEWDOG_GITHUB_API_TOKEN

  when:
    event:
      - pull_request
