kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: python:3.8
  volumes:
    - name: src
      path: /src
  commands:
  - python src/main.py

volumes:
  - name: src
    host: 
      path: /src
