runner:
    pylint:
      cmd: flake8 ./ # (required)
      errorformat: # (optional if there is supported format for <tool-name>. see reviewdog -list)
        - "%f:%l:%c: %m"
      name: reviewdog # (optional. you can overwrite <tool-name> defined by runner key)
      level: info
